// Auto-generated by scripts/generate-plugin-registry.mjs
// Nicht manuell bearbeiten.

import type { ComponentType, LazyExoticComponent } from 'react';
import * as plugin_crm_0 from '../../plugins/crm/frontend/index';
import * as plugin_quicklinks_1 from '../../plugins/quicklinks/frontend/index';
import * as plugin_todo_2 from '../../plugins/todo/frontend/index';

export interface PluginRoute {
    path: string;
    component: LazyExoticComponent<ComponentType<any>>;
    permission?: string;
    /** Route ist auf Public-Hosts ohne Workspace-Login zugreifbar */
    public?: boolean;
    /** Optionales Host-Allowlisting (z.B. ['kundenportal.example.de', '*.kunden.example.de']) */
    allowedHosts?: string[];
}

export interface PluginNavItem {
    label: string;
    icon: string;
    path: string;
    permission?: string;
    order: number;
    group?: string;
    groupIcon?: string;
    groupOrder?: number;
}

export interface PluginDashboardTile {
    id: string;
    title: string;
    description?: string;
    component: LazyExoticComponent<ComponentType<any>>;
    permission?: string;
    order?: number;
    /** @deprecated Verwende defaultWidth/defaultHeight. Wird automatisch migriert. */
    defaultSize?: 'small' | 'medium' | 'large';
    /** Breite in Grid-Units (1 Unit = 20px). Default: 12 */
    defaultWidth?: number;
    /** Höhe in Grid-Units (1 Unit = 20px). Default: 8 */
    defaultHeight?: number;
    defaultVisible?: boolean;
    /** Optionale Darstellungsmodi fuer die Kachel (z.B. Liste/Spalten) */
    viewModes?: Array<{ id: string; label: string }>;
    /** Default-ViewMode-ID fuer die Tile-Komponente */
    defaultViewMode?: string;
}

export interface PluginExtensionTile {
    id: string;
    targetSlot: string;
    title: string;
    description?: string;
    component: LazyExoticComponent<ComponentType<any>>;
    permission?: string;
    order?: number;
    defaultSize?: 'small' | 'medium' | 'large';
}

export interface PluginSettingsPanel {
    component: LazyExoticComponent<ComponentType<any>>;
    permission?: string;
}

export interface PluginSearchResult {
    title: string;
    description?: string;
    path: string;
    icon?: string;
}

export interface PluginSearchProvider {
    label: string;
    search: (query: string) => Promise<PluginSearchResult[]>;
    permission?: string;
}

export interface PluginQuickAction {
    id: string;
    label: string;
    icon?: string;
    keywords?: string[];
    permission?: string;
    execute: () => void | Promise<void>;
}

export interface PluginRegistryEntry {
    id: string;
    name: string;
    routes: PluginRoute[];
    navItems: PluginNavItem[];
    dashboardTiles: PluginDashboardTile[];
    extensionTiles: PluginExtensionTile[];
    settingsPanel?: PluginSettingsPanel;
    searchProvider?: PluginSearchProvider;
    quickActions?: PluginQuickAction[];
}

export const pluginRegistry: PluginRegistryEntry[] = [
    {
        id: 'crm',
        name: 'CRM',
        routes: (Array.isArray((plugin_crm_0 as any).routes) ? (plugin_crm_0 as any).routes : []) as PluginRoute[],
        navItems: (Array.isArray((plugin_crm_0 as any).navItems) ? (plugin_crm_0 as any).navItems : []) as PluginNavItem[],
        dashboardTiles: (Array.isArray((plugin_crm_0 as any).dashboardTiles) ? (plugin_crm_0 as any).dashboardTiles : []) as PluginDashboardTile[],
        extensionTiles: (Array.isArray((plugin_crm_0 as any).extensionTiles) ? (plugin_crm_0 as any).extensionTiles : []) as PluginExtensionTile[],
        settingsPanel: ((plugin_crm_0 as any).settingsPanel && typeof (plugin_crm_0 as any).settingsPanel === 'object' ? (plugin_crm_0 as any).settingsPanel : undefined) as PluginSettingsPanel | undefined,
        searchProvider: ((plugin_crm_0 as any).searchProvider && typeof (plugin_crm_0 as any).searchProvider === 'object' ? (plugin_crm_0 as any).searchProvider : undefined) as PluginSearchProvider | undefined,
        quickActions: (Array.isArray((plugin_crm_0 as any).quickActions) ? (plugin_crm_0 as any).quickActions : []) as PluginQuickAction[],
    },
    {
        id: 'quicklinks',
        name: 'Schnellzugriff',
        routes: (Array.isArray((plugin_quicklinks_1 as any).routes) ? (plugin_quicklinks_1 as any).routes : []) as PluginRoute[],
        navItems: (Array.isArray((plugin_quicklinks_1 as any).navItems) ? (plugin_quicklinks_1 as any).navItems : []) as PluginNavItem[],
        dashboardTiles: (Array.isArray((plugin_quicklinks_1 as any).dashboardTiles) ? (plugin_quicklinks_1 as any).dashboardTiles : []) as PluginDashboardTile[],
        extensionTiles: (Array.isArray((plugin_quicklinks_1 as any).extensionTiles) ? (plugin_quicklinks_1 as any).extensionTiles : []) as PluginExtensionTile[],
        settingsPanel: ((plugin_quicklinks_1 as any).settingsPanel && typeof (plugin_quicklinks_1 as any).settingsPanel === 'object' ? (plugin_quicklinks_1 as any).settingsPanel : undefined) as PluginSettingsPanel | undefined,
        searchProvider: ((plugin_quicklinks_1 as any).searchProvider && typeof (plugin_quicklinks_1 as any).searchProvider === 'object' ? (plugin_quicklinks_1 as any).searchProvider : undefined) as PluginSearchProvider | undefined,
        quickActions: (Array.isArray((plugin_quicklinks_1 as any).quickActions) ? (plugin_quicklinks_1 as any).quickActions : []) as PluginQuickAction[],
    },
    {
        id: 'todo',
        name: 'Aufgaben',
        routes: (Array.isArray((plugin_todo_2 as any).routes) ? (plugin_todo_2 as any).routes : []) as PluginRoute[],
        navItems: (Array.isArray((plugin_todo_2 as any).navItems) ? (plugin_todo_2 as any).navItems : []) as PluginNavItem[],
        dashboardTiles: (Array.isArray((plugin_todo_2 as any).dashboardTiles) ? (plugin_todo_2 as any).dashboardTiles : []) as PluginDashboardTile[],
        extensionTiles: (Array.isArray((plugin_todo_2 as any).extensionTiles) ? (plugin_todo_2 as any).extensionTiles : []) as PluginExtensionTile[],
        settingsPanel: ((plugin_todo_2 as any).settingsPanel && typeof (plugin_todo_2 as any).settingsPanel === 'object' ? (plugin_todo_2 as any).settingsPanel : undefined) as PluginSettingsPanel | undefined,
        searchProvider: ((plugin_todo_2 as any).searchProvider && typeof (plugin_todo_2 as any).searchProvider === 'object' ? (plugin_todo_2 as any).searchProvider : undefined) as PluginSearchProvider | undefined,
        quickActions: (Array.isArray((plugin_todo_2 as any).quickActions) ? (plugin_todo_2 as any).quickActions : []) as PluginQuickAction[],
    }
];
